// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7YtAXaiFGB0-ognGQHE88lIwvAFachG8',
    appId: '1:613015837624:web:e9f37a5f8c5d770a0f0d4d',
    messagingSenderId: '613015837624',
    projectId: 'noteapp-31539',
    authDomain: 'noteapp-31539.firebaseapp.com',
    storageBucket: 'noteapp-31539.firebasestorage.app',
    measurementId: 'G-NSQ3SNVLNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmtAOJeMaO971GzmGraLByP0DHT5YL2o4',
    appId: '1:613015837624:android:3bd5e1598f21b2a40f0d4d',
    messagingSenderId: '613015837624',
    projectId: 'noteapp-31539',
    storageBucket: 'noteapp-31539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnXPzubVvpZ4XaPSl9uYEgmpyVkJbajT4',
    appId: '1:613015837624:ios:b68482561bdd47b90f0d4d',
    messagingSenderId: '613015837624',
    projectId: 'noteapp-31539',
    storageBucket: 'noteapp-31539.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnXPzubVvpZ4XaPSl9uYEgmpyVkJbajT4',
    appId: '1:613015837624:ios:b68482561bdd47b90f0d4d',
    messagingSenderId: '613015837624',
    projectId: 'noteapp-31539',
    storageBucket: 'noteapp-31539.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7YtAXaiFGB0-ognGQHE88lIwvAFachG8',
    appId: '1:613015837624:web:d92916f24bd759ce0f0d4d',
    messagingSenderId: '613015837624',
    projectId: 'noteapp-31539',
    authDomain: 'noteapp-31539.firebaseapp.com',
    storageBucket: 'noteapp-31539.firebasestorage.app',
    measurementId: 'G-JCSF72XG8D',
  );
}
